spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: info

server:
  forward-headers-strategy: framework