server:
  port: ${PORT:8081}

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        use_sql_comments: true

ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8000}

jwt:
  secret: ${JWT_SECRET}
  access-expiry: 3600000       # 1시간 (ms)
  refresh-expiry: 1209600000   # 14일 (ms)

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-southeast-2
    s3:
      bucket: ${S3_BUCKET_NAME}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true